services:

  db:
    build: ./data/
    volumes:
      - ./data/mysql_data:/var/lib/mysql         # perpetuation of data
      - ./data/sqls:/docker-entrypoint-initdb.d  # pushing initial data
      - ./data/logs:/var/log/mysql               # log record
    environment:
      - MYSQL_USER=share_user
      - MYSQL_DATABASE=share_database
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass

  appserver:
    build: ./api/
    ports:
      - 8080:8080
    volumes:
      - ./api:/go/src/github.com/api
    environment:
      TZ: Asia/Tokyo
    tty: true
    depends_on:
      - db
    env_file:
      - ./api/.go_env
    command: sh -c "go run ./cmd/main.go"

