services:

  db:
    build: ./mysql/
    volumes:
      - ./data/mysql_data:/var/lib/mysql         # perpetuation of data
      - ./data/sqls:/docker-entrypoint-initdb.d  # pushing initial data
      - ./data/logs:/var/log/mysql               # log record
    environment:
      - MYSQL_USER=share_user
      - MYSQL_DATABASE=share_database
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass

  appserver:
    build: ./app/
    ports:
      - 8080:8080
    volumes:
      - ./api/cmd:/workdir
    environment:
      TZ: Asia/Tokyo
    tty: true
    links:
      - db
